import pprint

id_ = "python_01"
subject_name = "Python"

description_video = "http://www.youtube.com/embed/x9gjp2xYZ3k?rel=0"

description = """\
"""

price = 500

time = "10 堂課"

summary = """\
Python"""

link = ""
image = "class_python.png"

title_list = [
	"第一課 與 Python 相遇",
	"第二課 運算、字串與變數",
	"第三課 資料類型",
	"第四課 Debug",
	"第五課 Functions",
	"第六課 GUIs",
	"第七課 做決定",
	"第八課 列表",
	"第九課 迴圈",
	"第十課 File I/O",
	]

class_list = [
	('1-1 與 Python 相遇', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-1.mp4', []),
	('1-2 程式語言', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-2.mp4', []),
	('1-3 基本的程式指令', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-3.mp4', []),
	('1-4 Scratch 程式積木', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-4.mp4', []),
	('1-5 安裝程式', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-5.mp4', []),
	('1-6 Python IDLE', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-6.mp4', []),
	('1-7 第一行程式', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-7.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-7-answer.mp4'),
	('1-8 提示符號 >>>', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-8.mp4', []),
	('1-9 print()', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-9.mp4', []),
	('1-10 色彩繽紛的程式', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-10.mp4', []),
	('1-11 錯誤訊息', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-11.mp4', []),
	('1-12 小試身手-1', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-12.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-12-answer.mp4'),
	('1-13 小試身手-2', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-13.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-13-answer.mp4'),
	('1-14 小試身手-3', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-14.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-14-answer.mp4'),
	('1-15 小試身手-4', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-15.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-15-answer.mp4'),
	('1-16 小試身手-5', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-16.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-16-answer.mp4'),
	('1-17 小試身手-6', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-17.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-17-answer.mp4'),
	('1-18 第一個程式', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-18.mp4', []),
	('1-19 互動模式與檔案模式', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-19.mp4', []),
	('1-20 調整字體', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-20.mp4', []),
	('1-21 複製貼上', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-21.mp4', []),
	('1-22 讀取檔案', 'http://storage.googleapis.com/coding4fun-class-video/python-01/1-22.mp4', []),
	('2-1 加減乘除', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-1.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-1-answer.mp4'),
	('2-2 小試身手-1', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-2.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-2-answer.mp4'),
	('2-3 二進位', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-3.mp4', []),
	('2-4 數字類型', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-4.mp4', []),
	('2-5 運算子', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-5.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-5-answer.mp4'),
	('2-6 計算規則', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-6.mp4', []),
	('2-7 指數-1', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-7.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-7-answer.mp4'),
	('2-8 指數-2', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-8.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-8-answer.mp4'),
	('2-9 小試身手-2', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-9.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-9-answer.mp4'),
	('2-10 小試身手-3', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-10.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-10-answer.mp4'),
	('2-11 小試身手-4', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-11.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-11-answer.mp4'),
	('2-12 餘數', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-12.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-12-answer.mp4'),
	('2-13 小試身手-5', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-13.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-13-answer.mp4'),
	('2-14 小試身手-6', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-14.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-14-answer.mp4'),
	('2-15 小試身手-7', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-15.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-15-answer.mp4'),
	('2-16 字串', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-16.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-16-answer.mp4'),
	('2-17 引號', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-17.mp4', []),
	('2-18 長字串', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-18.mp4', []),
	('2-19 字串的運算', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-19.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-19-answer.mp4'),
	('2-20 小試身手-8', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-20.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-20-answer.mp4'),
	('2-21 小試身手-9', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-21.mp4', []),
	('2-22 小試身手-10', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-22.mp4', []),
	('2-23 len()', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-23.mp4', []),
	('2-24 程式三要素', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-24.mp4', []),
	('2-25 名稱', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-25.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-25-answer.mp4'),
	('2-26 小試身手-11', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-26.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-26-answer.mp4'),
	('2-27 小試身手-12', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-27.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-27-answer.mp4'),
	('2-28 變數', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-28.mp4', []),
	('2-29 小試身手-13', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-29.mp4', []),
	('2-30 小試身手-14', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-30.mp4', []),
	('2-31 小試身手-15', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-31.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-31-answer.mp4'),
	('2-32 增加', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-32.mp4', []),
	('2-33 減少', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-33.mp4', []),
	('2-34 定義變數', 'http://storage.googleapis.com/coding4fun-class-video/python-01/2-34.mp4', []),
	('3-1 資料類型與type()', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-1.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-1-answer.mp4'),
	('3-2 資料類型的轉換', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-2.mp4', []),
	('3-3 float()', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-3.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-3-answer.mp4'),
	('3-4 小試身手-1', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-4.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-4-answer.mp4'),
	('3-5 小試身手-2', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-5.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-5-answer.mp4'),
	('3-6 小試身手-3', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-6.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-6-answer.mp4'),
	('3-7 int()', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-7.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-7-answer.mp4'),
	('3-8 小試身手-4', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-8.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-8-answer.mp4'),
	('3-9 小試身手-5', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-9.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-9-answer.mp4'),
	('3-10 小試身手-6', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-10.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-10-answer.mp4'),
	('3-11 小試身手-7', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-11.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-11-answer.mp4'),
	('3-12 小試身手-8', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-12.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-12-answer.mp4'),
	('3-13 str()', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-13.mp4', []),
	('3-14 小試身手-9', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-14.mp4', []),
	('3-15 input()', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-15.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-15-answer.mp4'),
	('3-16 小試身手-10', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-16.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-16-answer.mp4'),
	('3-17 小試身手-11', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-17.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-17-answer.mp4'),
	('3-18 小試身手-12', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-18.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-18-answer.mp4'),
	('3-19 小試身手-13', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-19.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-19-answer.mp4'),
	('3-20 猜數字遊戲', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-20.mp4', []),
	('3-21 說明', 'http://storage.googleapis.com/coding4fun-class-video/python-01/3-21.mp4', []),
	('4-1 Debug', 'http://storage.googleapis.com/coding4fun-class-video/python-01/4-1.mp4', []),
	('4-2 語法錯誤', 'http://storage.googleapis.com/coding4fun-class-video/python-01/4-2.mp4', []),
	('4-3 語法常見的錯誤', 'http://storage.googleapis.com/coding4fun-class-video/python-01/4-3.mp4', []),
	('4-4 執行階段錯誤', 'http://storage.googleapis.com/coding4fun-class-video/python-01/4-4.mp4', []),
	('4-5 錯誤訊息', 'http://storage.googleapis.com/coding4fun-class-video/python-01/4-5.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/4-5-answer.mp4'),
	('4-6 拼字錯誤', 'http://storage.googleapis.com/coding4fun-class-video/python-01/4-6.mp4', []),
	('4-7 縮格錯誤', 'http://storage.googleapis.com/coding4fun-class-video/python-01/4-7.mp4', []),
	('4-8 常見錯誤', 'http://storage.googleapis.com/coding4fun-class-video/python-01/4-8.mp4', []),
	('4-9 邏輯錯誤', 'http://storage.googleapis.com/coding4fun-class-video/python-01/4-9.mp4', []),
	('4-10 小試身手-1', 'http://storage.googleapis.com/coding4fun-class-video/python-01/4-10.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/4-10-answer.mp4'),
	('4-11 小試身手-2', 'http://storage.googleapis.com/coding4fun-class-video/python-01/4-11.mp4', []),
	('4-12 註解', 'http://storage.googleapis.com/coding4fun-class-video/python-01/4-12.mp4', []),
	('5-1 什麼是function', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-1.mp4', []),
	('5-2 內建 functions', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-2.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-2-answer.mp4'),
	('5-3 模組', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-3.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-3-answer.mp4'),
	('5-4 小試身手-1', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-4.mp4', []),
	('5-5 小試身手-2', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-5.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-5-answer.mp4'),
	('5-6 小試身手-3', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-6.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-6-answer.mp4'),
	('5-7 小試身手-4', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-7.mp4', []),
	('5-8 定義自己的 functions', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-8.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-8-answer.mp4'),
	('5-9 小試身手-5', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-9.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-9-answer.mp4'),
	('5-10 執行程式', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-10.mp4', []),
	('5-11 小試身手-6', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-11.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-11-answer.mp4'),
	('5-12 小試身手-7', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-12.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-12-answer.mp4'),
	('5-13 小試身手-8', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-13.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-13-answer.mp4'),
	('5-14 傳入參數', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-14.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-14-answer.mp4'),
	('5-15 小試身手-9', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-15.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-15-answer.mp4'),
	('5-16 小試身手-10', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-16.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-16-answer.mp4'),
	('5-17 傳入兩個參數', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-17.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-17-answer.mp4'),
	('5-18 傳入更多參數', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-18.mp4', []),
	('5-19 小試身手-11', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-19.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-19-answer.mp4'),
	('5-20 print()', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-20.mp4', []),
	('5-21 傳回值', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-21.mp4', []),
	('5-22 小試身手-12', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-22.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-22-answer.mp4'),
	('5-23 小試身手-13', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-23.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-23-answer.mp4'),
	('5-24 小試身手-14', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-24.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-24-answer.mp4'),
	('5-25 中文名稱', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-25.mp4', []),
	('5-26 變數的作用範圍', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-26.mp4', []),
	('5-27 區域變數', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-27.mp4', [], 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-27-answer.mp4'),
	('5-28 全域變數', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-28.mp4', []),
	('5-29 命名建議-1', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-29.mp4', []),
	('5-30 命名建議-2', 'http://storage.googleapis.com/coding4fun-class-video/python-01/5-30.mp4', []),
	('6-1 安裝 easygui',  'http://storage.googleapis.com/coding4fun-class-video/python-01/6-1.mp4',  []),
	('6-2 msgbox()',  'http://storage.googleapis.com/coding4fun-class-video/python-01/6-2.mp4',  []),
	('6-3 儲存傳回的值',  'http://storage.googleapis.com/coding4fun-class-video/python-01/6-3.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/6-3-answer.mp4'),
	('6-4 buttonbox()',  'http://storage.googleapis.com/coding4fun-class-video/python-01/6-4.mp4',  []),
	('6-5 choicebox()',  'http://storage.googleapis.com/coding4fun-class-video/python-01/6-5.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/6-5-answer.mp4'),
	('6-6 enterbox()',  'http://storage.googleapis.com/coding4fun-class-video/python-01/6-6.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/6-6-answer.mp4'),
	('6-7 integerbox()',  'http://storage.googleapis.com/coding4fun-class-video/python-01/6-7.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/6-7-answer.mp4'),
	('6-8 改寫猜數字遊戲',  'http://storage.googleapis.com/coding4fun-class-video/python-01/6-8.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/6-8-answer.mp4'),
	('6-9 大展身手',  'http://storage.googleapis.com/coding4fun-class-video/python-01/6-9.mp4',  []),
	('7-1 做決定',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-1.mp4',  []),
	('7-2 條件',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-2.mp4',  []),
	('7-3 if 和 else',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-3.mp4',  []),
	('7-4 陳述句與疑問句',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-4.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-4-answer.mp4'),
	('7-5 小試身手-1',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-5.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-5-answer.mp4'),
	('7-6 邏輯運算',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-6.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-6-answer.mp4'),
	('7-7 小試身手-2',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-7.mp4',  []),
	('7-8 小試身手-3',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-8.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-8-answer.mp4'),
	('7-9 運算子 and',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-9.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-9-answer.mp4'),
	('7-10 小試身手-4',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-10.mp4',  []),
	('7-11 運算子 or',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-11.mp4',  []),
	('7-12 運算子 not',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-12.mp4',  []),
	('7-13 小試身手-5',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-13.mp4',  []),
	('7-14 elif',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-14.mp4',  []),
	('7-15 分支',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-15.mp4',  []),
	('7-16 更多的 elif',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-16.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-16-answer.mp4'),
	('7-17 解說-1',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-17.mp4',  []),
	('7-18 解說-2',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-18.mp4',  []),
	('7-19 小試身手-6',  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-19.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/7-19-answer.mp4'),
	('8-1 列表',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-1.mp4',  []),
	('8-2 建立列表',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-2.mp4',  []),
	('8-3 append()',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-3.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-3-answer.mp4'),
	('8-4 小試身手-1',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-4.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-4-answer.mp4'),
	('8-5 點',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-5.mp4',  []),
	('8-6 存放資料的種類',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-6.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-6-answer.mp4'),
	('8-7 讀取列表',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-7.mp4',  []),
	('8-8 為什麼 index 從 0 開始',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-8.mp4',  []),
	('8-9 運算子 ＋',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-9.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-9-answer.mp4'),
	('8-10 小試身手-2',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-10.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-10-answer.mp4'),
	('8-11 運算子 *',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-11.mp4',  []),
	('8-12 修改項目',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-12.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-12-answer.mp4'),
	('8-13 小試身手-3',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-13.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-13-answer.mp4'),
	('8-14 在列表中加入項目',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-14.mp4',  []),
	('8-15 加入方法一：append()',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-15.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-15-answer.mp4'),
	('8-16 小試身手-4',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-16.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-16-answer.mp4'),
	('8-17 小試身手-5',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-17.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-17-answer.mp4'),
	('8-18 加入方法二：extend()',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-18.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-18-answer.mp4'),
	('8-19 加入方法三：insert()',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-19.mp4',  []),
	('8-20 小試身手-6',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-20.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-20-answer.mp4'),
	('8-21 append() 和 extend() 的差別',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-21.mp4',  []),
	('8-22 移除方法一：remove()',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-22.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-22-answer.mp4'),
	('8-23 小試身手-7',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-23.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-23-answer.mp4'),
	('8-24 關鍵字 in',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-24.mp4',  []),
	('8-25 小試身手-8',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-25.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-25-answer.mp4'),
	('8-26 移除方法二：del',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-26.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-26-answer.mp4'),
	('8-27 小試身手-9',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-27.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-27-answer.mp4'),
	('8-28 小試身手-10',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-28.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-28-answer.mp4'),
	('8-29 移除方法三：pop()',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-29.mp4',  []),
	('8-30 小試身手-11',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-30.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-30-answer.mp4'),
	('8-31 小試身手-12',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-31.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-31-answer.mp4'),
	('8-32 pop(index)',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-32.mp4',  []),
	('8-33 在列表中尋找',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-33.mp4',  []),
	('8-34 小試身手-13',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-34.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-34-answer.mp4'),
	('8-35 透過列表做重複執行',  'http://storage.googleapis.com/coding4fun-class-video/python-01/8-35.mp4',  []),
	('9-1 迴圈',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-1.mp4',  []),
	('9-2 計算次數的迴圈',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-2.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-2-answer.mp4'),
	('9-3 for loop',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-3.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-3-answer.mp4'),
	('9-4 逃脫之術',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-4.mp4',  []),
	('9-5 乘法表',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-5.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-5-answer.mp4'),
	('9-6 range()',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-6.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-6-answer.mp4'),
	('9-7 小試身手-1',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-7.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-7-answer.mp4'),
	('9-8 小試身手-2',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-8.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-8-answer.mp4'),
	('9-9 Loop 變數',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-9.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-9-answer.mp4'),
	('9-10 range(n) 從 0 開始',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-10.mp4',  []),
	('9-11 小試身手-3',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-11.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-11-answer.mp4'),
	('9-12 小試身手-4',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-12.mp4',  []),
	('9-13 Step',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-13.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-13-answer.mp4'),
	('9-14 小試身手-5',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-14.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-14-answer.mp4'),
	('9-15 倒數計時',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-15.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-15-answer.mp4'),
	('9-16 不同的參數數目',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-16.mp4',  []),
	('9-17 字串列表',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-17.mp4',  []),
	('9-18 條件型的迴圈 while loop',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-18.mp4',  []),
	('9-19 while loop',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-19.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-19-answer.mp4'),
	('9-20 迴圈控制',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-20.mp4',  []),
	('9-21 continue',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-21.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-21-answer.mp4'),
	('9-22 break',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-22.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-22-answer.mp4'),
	('9-23 continue 和 break 的差別',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-23.mp4',  []),
	('9-24 與 Scratch 相對應',  'http://storage.googleapis.com/coding4fun-class-video/python-01/9-24.mp4',  []),
	('10-1 檔案特性',  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-1.mp4',  []),
	('10-2 檔案名稱與類型',  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-2.mp4',  []),
	('10-3 檔案位置',  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-3.mp4',  []),
	('10-4 路徑',  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-4.mp4',  []),
	('10-5 存取檔案',  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-5.mp4',  []),
	("10-6 寫檔案 'w'",  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-6.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-6-answer.mp4'),
	('10-7 小試身手-1',  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-7.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-7-answer.mp4'),
	('10-8 小試身手-2',  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-8.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-8-answer.mp4'),
	("10-9 寫檔案 'a'",  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-9.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-9-answer.mp4'),
	('10-10 小試身手-3',  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-10.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-10-answer.mp4'),
	("10-11 讀檔案 'r'",  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-11.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-11-answer.mp4'),
	('10-12 readline()',  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-12.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-12-answer.mp4'),
	('10-13 readlines()',  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-13.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-13-answer.mp4'),
	('10-14 二進位檔案',  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-14.mp4',  [],  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-14-answer.mp4'),
	('10-15 工作目錄',  'http://storage.googleapis.com/coding4fun-class-video/python-01/10-15.mp4',  []),
	]


json = {
	"subject":subject_name,
	"info":[],
	"summary": summary,
	"description-video": description_video,
	"description": description,
	"price":price,
	"link":link,
	"image":image,
	"time": time,
	"titles": title_list,
	"id": id_,
	}

for i in class_list:
	a = i[0].split()

	unit, _ = map(int, a[0].split("-"))
	if len(json["info"]) < unit:
		json["info"].append([])

	class_ = {
		"class_name": i[0],
		"video": i[1],
		"description":"",
		"answer": "",
		"buttons": i[2],
		}
	if len(i) == 4:
		class_["answer"] = i[3]
	json["info"][unit - 1].append(class_)

pprint.pprint(json)
print("\n\n")

change = input("確定要存擋? %s (Y/N)" % (id_ + ".json")).lower()
if change != "y":
	exit()

file = open(id_ + ".json", "w")
file.write(pprint.pformat(json))
file.close()

print("存擋成功")
